site_name: Dr. Down
site_description: 'Sistema direcionado a auxiliar o cuidado de pessoas com Síndrome de Down'
repo_url: https://github.com/fga-gpp-mds/2018.1-Dr-Down
theme: readthedocs

pages:
  - Home: index.md
  - Abertura:
    - Termo de abertura: eps/TAP.md
    - EAP: eps/EAP.md
    - Código de conduta: CODE_OF_CONDUCT.md
    - Canvas: eps/CANVAS.md
  - Especificação:
    - Documento de visão: mds/VISION_DOCUMENT.md
    - Documento de arquitetura: mds/ARCHITECTURE_DOCUMENT.md
    - Especificação Suplementar: mds/ADDITIONAL_SPECIFICATION.md
    - Mapa de Requisitos: eps/REQUIREMENTS_MAP.md
    - Gerenciamento de Qualidade: eps/QUALITY_MANAGEMENT_PLAN.md
    - ROADMAP: eps/ROADMAP.md
    - ROADMAP dos Papéis: eps/ROADMAP_ROLES.md
    - MINDMAP: eps/MINDMAP.md
    - Protótipo de baixa qualidade: mds/LOW_FIDELITY_PROTOTYPE.md
    - Protótipo de alta qualidade: mds/HIGH_FIDELITY_PROTOTYPE.md
  - Viabilidade Técnica:
    - Metodologia: eps/SCRUM_METHODOLOGY_DRDOWN.md
    - Definição de Pronto: eps/DONE_DEFINITION.md
    - EVM: eps/EVM_AGILE.md
    - Ferramentas: eps/PROJECT_TOOLS.md
    - Riscos: eps/RISKS.md
    - Pipeline: eps/PIPELINE.md
  - Testes de Usabilidade:
    - Introdução: eps/usability_test/USABILITY_TESTS.md
    - Relatório 01: eps/usability_test/relatorio_01.md
    - Relatório 02: eps/usability_test/relatorio_02.md
    - Relatório 03: eps/usability_test/relatorio_03.md
    - Relatório 04: eps/usability_test/relatorio_04.md
    - Relatório 05: eps/usability_test/relatorio_05.md
  - Sprint 0:
    - Planejamento: sprints/00/planning.md
    - Resultado: sprints/00/results.md
  - Sprint 1:
    - Planejamento: sprints/01/planning.md
    - Resultado: sprints/01/results.md
  - Sprint 2:
    - Planejamento: sprints/02/planning.md
    - Resultado: sprints/02/results.md
  - Sprint 3:
    - Planejamento: sprints/03/planning.md
    - Resultado: sprints/03/results.md
  - Sprint 4:
    - Planejamento: sprints/04/planning.md
    - Resultado: sprints/04/results.md
  - Sprint 5:
    - Planejamento: sprints/05/planning.md
    - Resultado: sprints/05/results.md
  - Sprint 6:
    - Planejamento: sprints/06/planning.md
    - Resultado: sprints/06/results.md
  - Sprint 7:
    - Planejamento: sprints/07/planning.md
    - Resultado: sprints/07/results.md
  - Sprint 8:
    - Planejamento: sprints/08/planning.md
    - Resultado: sprints/08/results.md
  - Sprint 9:
    - Planejamento: sprints/09/planning.md
    - Resultado: sprints/09/results.md
  - Sprint 10:
    - Planejamento: sprints/10/planning.md
    - Resultado: sprints/10/results.md
  - Sprint 11:
    - Planejamento: sprints/11/planning.md
    - Resultado: sprints/11/results.md
  - Sprint 12:
    - Planejamento: sprints/12/planning.md
    - Resultado: sprints/12/results.md
  - Sprint 13:
    - Planejamento: sprints/13/planning.md
    - Resultado: sprints/13/results.md
  - Sprint 14:
    - Planejamento: sprints/14/planning.md
    - Resultado: sprints/14/results.md
